name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: mvn verify
      id: mvn-verify
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: mvn verify
        setup-command: mvn clean install
        command: mvn verify
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MVN-VERIFY_RESULTS: "${{steps.mvn-verify.outputs.result}}"
      with:
        runners: mvn-verify
